language: go
# Using sudo triggers a real virtual machine as opposed to a container, which
# allows ghw to actually determine things like host memory or block storage...
sudo: required
os:
  - windows
  - linux
  - osx
install:
  - go get -u github.com/golang/dep/cmd/dep
before_script:
  - dep ensure -v
  - source ./.get-go-packages.sh
script:
  - make test
  - go run cmd/ghwc/main.go
